### ISSUE TITLE
Getting 404 on the login URL

### ISSUE THREAD

**Issue by aaronpk** [aaronpowell/swa-custom-auth-okta#1]
First of all, thanks for the excellent writeup in this post! https://techcommunity.microsoft.com/t5/apps-on-azure/using-okta-with-static-web-apps/ba-p/2353700

This is exactly what I am trying to do. I went through all the steps, created the config file, but am unable to actually get this to work with Okta. When I visit the `/.auth/login/okta` URL on my Azure app, it just returns 404 Not found.

I've double checked that my `staticwebapp.config.json` matches yours. I've even configured a GitHub provider and the `/.auth/login/github` URL works fine.

Are there any other steps I need to do in Azure to get this to work?

**Comment by aaronpowell** [comment]
Are you using the Standard Tier of static web apps? Custom OIDC providers are only supported there.

Otherwise, do you have a repo I could look at?

**Comment by aaronpk** [comment]
aha! That is the missing piece. I am brand new to Azure, literally just signed up for it a few hours ago for this purpose, so I was not familiar with the terminology, and definitely did not realize that "Standard Tier" refers to a billing scheme! This works swimmingly now.

**Comment by aaronpowell** [comment]
The tiering is used to change feature availablity and imply the usage intent. Free is really for simple apps and non-prod stuff (lacks SLA and a few things like that).

https://azure.microsoft.com/en-au/pricing/details/app-service/static/ has all the differences between the tiers ☺️

**Comment by ChuckJonas** [comment]
Can you please add that very important detail to your readme and or blog... I just wasted so much time...

**Comment by aaronpowell** [comment]
@ChuckJonas it's in the first line of the blog post that I link to from the readme of the repo.

**Comment by ChuckJonas** [comment]
doh... sorry.

Although, I'd say that detail is important enough that it might actually warrant a bit more exposure (maybe a "note" where you say to deploy the app).

If you wanted to improve your blog post, you might even consider adding a section that actually walks through deployment steps.

Thanks.
